#!/usr/bin/env python
import os
from diffusers import StableDiffusionInpaintPipeline


model_id = "e5a34f913de0adc560d20e002c45ad43a80031b62caacc3d84010c6b6a64870c"
MODEL_CACHE = "diffusers-cache"
os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = StableDiffusionInpaintPipeline.from_pretrained(
    model_id,
    cache_dir=MODEL_CACHE,
)